### ISSUE TITLE
ES6? When?

### ISSUE THREAD

**Issue by z3dev** [drom/onml#9]
@drom are there any plans to convert this library to ES6 import/export?

**Comment by drom** [comment]
@z3dev great to hear from you!
This is a very good question. I don't use ES6 import/export module system in any of my projects yet, but I see more and more projects switching. If I switch, I still want to keep CommonJS compatible version in the same package. I guess I could rewrite in import/export style and then use Babel to transpile into CommonJS.

I have seen CodeMirror 6 is distributing transpiled CommonJS version. But I have to do:
```
const {EditorState} = require('@codemirror/state/dist/index.cjs');
```
instead of:
```
const {EditorState} = require('@codemirror/state');
```
Is it reasonable?
Do you know of way of having 2 "main" entry points in my package?
Do you plan to switch JSCAD packages to import/export module system?

I should read more here: https://nodejs.org/api/modules.html#enabling

**Comment by z3dev** [comment]
> 

Hi @drom 
Yup. JSCAD is moving to ES6 as we speak. It's a BIG jump but things are moving along.

You're correct. You will have to either convert from CommonJS code to ESM module, or convert from ESM code to CommonJS module.

For JSCAD, we are converting the code to ESM standard. A few things will probably break.
The WEB UI has some dependencies that will never be ESM, but we are re-writing that as well to get rid of 'most' frameworks.

I've been playing with Rollup to build both CommonJS and ESM libraries. It's really simple. ONML should have no issues supplying both to the world. I believe most open source projects are following the same.

**Comment by drom** [comment]
I have build simple ESM project and imported existing ONML without problem. What kind of error do you have?

```js
import onml from 'onml';

console.log(onml.stringify);
```

Here is the project: https://github.com/drom/esm-playground

Works in Node 12,14,16,18,19
